### Train
POST http://localhost:7301/api/v1/ai/train
Content-Type: application/json
Accept: application/json

{
  "symbol": "$SPX",
  "startDate": "2025-12-29T00:00:00.000000",
  "endDate": "2026-02-10T15:00:00.000000",
  "predictionHorizon": 60,
  "modelType": "lstm",
  "numEpochs": 50,
  "batchSize": 64,
  "learningRate": 0.001,
  "l2Regularization": 0.0001,
  "seed": 137,
  "trainRatio": 0.7,
  "validationRatio": 0.15,
  "earlyStoppingPatience": 10,
  "useLearningRateDecay": true,
  "useTimeSeries": true,
  "sequenceLength": 15,
  "numSamples": 2340
}


### Predict
GET http://localhost:7301/api/v1/ai/predict/$SPX?minutesAhead=60
Content-Type: application/json
Accept: application/json


### Predict Multi-Horizon
GET http://localhost:7301/api/v1/ai/predict/multi-horizon/$SPX
Content-Type: application/json
Accept: application/json


### Feature Importance
GET http://localhost:7301/api/v1/ai/feature-importance/$SPX
Content-Type: application/json
Accept: application/json