CREATE TABLE ORDERS
(
    ID       BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ORDERID  BIGINT      NOT NULL,
    SYMBOL   TEXT        NOT NULL,
    QUANTITY DECIMAL     NOT NULL,
--     PRICE    DECIMAL     NOT NULL,
    TYPE     VARCHAR(25) NOT NULL,
    CREATED  TIMESTAMP   NOT NULL DEFAULT NOW(),
    FILLED   TIMESTAMP
);

CREATE TABLE POSITION
(
    ID            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    SYMBOL        TEXT        NOT NULL,
    TYPE          VARCHAR(25) NOT NULL,
    QUANTITY      DECIMAL     NOT NULL,
    PURCHASEPRICE DECIMAL     NOT NULL,
    CREATED       TIMESTAMP   NOT NULL DEFAULT NOW(),
    SELLPRICE     DECIMAL,
    CLOSED        TIMESTAMP
);

CREATE TABLE QUOTE
(
    ID            BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    SYMBOL        TEXT        NOT NULL,
    MARK      DECIMAL,
    OPEN      DECIMAL,
    CLOSE      DECIMAL,
    HIGH      DECIMAL,
    LOW      DECIMAL,
    CREATED       TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE TABLE SESSION
(
    ID                BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TOKEN             TEXT      NOT NULL,
    REFRESHTOKEN      TEXT      NOT NULL,
    CREATED           TIMESTAMP NOT NULL DEFAULT NOW(),
    LASTUPDATED       TIMESTAMP NOT NULL DEFAULT NOW(),
    REFRESHEXPIRATION TIMESTAMP,
    ACCESSEXPIRATION  TIMESTAMP
);
